name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-tests:
    uses: AstarVienna/DevOps/.github/workflows/tests.yml@master
