name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Runs at 05:00 UTC, only on Monday and Wednesday
    - cron: "0 5 * * MON,WED"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-tests:
    name: Offline tests
    uses: AstarVienna/DevOps/.github/workflows/tests.yml@main
    secrets: inherit

  call-updated-tests:
    name: Tests with updated dependencies
    uses: AstarVienna/DevOps/.github/workflows/updated_tests.yml@main
    secrets: inherit
